fix: codejail issue when using matplotlib
Upgrades numpy in the edx-sandbox to fix runtime error triggered by added test case:

    RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

The upgraded numpy now imports secrets, which requires random.SystemRandom, so
this change also adds SystemRandom to the random module overridden by the
safe_exec code prolog.

(cherry picked from commit e8b8147dcb9cf10ea555b201f87d93a5eee6a1b6)