Pulled transifex translations and tried to compile them.
However, it's failing at the "i18n_dummy" step, with:

CommandError: Execution of msgfmt failed: /edx/app/edxapp/edx-platform/conf/locale/fr/LC_MESSAGES/django.po:2704: a format specification for argument 'button_name' doesn't exist in 'msgstr'
msgfmt: found 1 fatal error