[FAL-1813] fix: codejail issue when using matplotlib (#343)
* test: skip added test_matplot in CI

Since the Jenkins CI doesn't run safe_exec in the sandbox virtualenv, matplotlib is not available.

(cherry picked from commit 1e7f563284ff92b77eac6db9c0ed43a29e6053f6)

* fix: codejail issue when using matplotlib

Upgrades numpy in the edx-sandbox to fix runtime error triggered by added test case:

    RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

The upgraded numpy now imports secrets, which requires random.SystemRandom, so
this change also adds SystemRandom to the random module overridden by the
safe_exec code prolog.

(cherry picked from commit e8b8147dcb9cf10ea555b201f87d93a5eee6a1b6)