Fix bug introduced when speeding up migrations for Django 1.8
cf https://github.com/open-craft/edx-platform/pull/121

The bug surfaces only when you fake a migration, as we do for djcelery
with Ginkgo.1:

...
  File "/edx/app/edxapp/edx-platform/lms/monkey_patch/django.py", line
282, in detect_soft_applied
    if isinstance(operation, migrations.CreateModel):
NameError: global name 'migrations' is not defined