Adds openedx.core.lib.xblock_builtin.xblock_capa_problems
First bash at moving the capa_module classes into a single XBlock.

This code throws warnings "Unable to load XBlock 'conditional'" because of the
moved shared file common/lib/xmodule/xmodule/css/capa/display.scss (and likely
because that module depends on CAPA).

The LMS loads, but when trying to view a problem, throws "AttributeError: 'CachingDescriptorSystem' object has no attribute 'set'"